// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SW.Store.Checkout.Infrastructure.ReadStorage.Database;

namespace SW.Store.Checkout.Infrastructure.ReadStorage.Migrations
{
    [DbContext(typeof(SwStoreReadDbContext))]
    [Migration("20181027164332_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SW.Store.Checkout.Read.ReadView.OrderLineReadView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("OrderId");

                    b.Property<int>("ProductId");

                    b.Property<int>("Quantity");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLineViews");
                });

            modelBuilder.Entity("SW.Store.Checkout.Read.ReadView.OrderReadView", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("OrderViews");
                });

            modelBuilder.Entity("SW.Store.Checkout.Read.ReadView.WarehouseItemReadView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProductId");

                    b.Property<int>("Quantity");

                    b.Property<Guid>("WarehouseId");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("WarehouseItemReadViews");
                });

            modelBuilder.Entity("SW.Store.Checkout.Read.ReadView.WarehouseReadView", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("WarehouseReadViews");
                });

            modelBuilder.Entity("SW.Store.Checkout.Read.ReadView.OrderLineReadView", b =>
                {
                    b.HasOne("SW.Store.Checkout.Read.ReadView.OrderReadView", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SW.Store.Checkout.Read.ReadView.WarehouseItemReadView", b =>
                {
                    b.HasOne("SW.Store.Checkout.Read.ReadView.WarehouseReadView", "Warehouse")
                        .WithMany("Items")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
